// Automatically generated file. Do not edit.
// Generated by embed-bytes crate.

pub struct ResourceContainerEmbeddedData;

impl ResourceContainerEmbeddedData {

    pub const LOCAL_FILE: &'static [u8] = include_bytes!("../embedded_data/LOCAL_FILE.bin");
    pub const REMOTE_FILE: &'static [u8] = include_bytes!("../embedded_data/REMOTE_FILE.bin");
    pub const ARBITRARY_DATA: &'static [u8] = include_bytes!("../embedded_data/ARBITRARY_DATA.bin");
}
