// Automatically generated file. Do not edit.
// Generated by embed-bytes crate.

pub struct ResourceContainerEmbeddedData;

impl ResourceContainerEmbeddedData {
    #[cfg(feature = "embed-bytes")]
    pub const LOCAL_FILE: &'static [u8] =
        include_bytes!(concat!(env!("OUT_DIR"), "/embed/LOCAL_FILE.bin"));

    #[cfg(not(feature = "embed-bytes"))]
    #[deprecated(note = "Feature flag not set, using empty array")]
    pub const LOCAL_FILE: &'static [u8] = &[];

    #[cfg(feature = "embed-bytes")]
    pub const REMOTE_FILE: &'static [u8] =
        include_bytes!(concat!(env!("OUT_DIR"), "/embed/REMOTE_FILE.bin"));

    #[cfg(not(feature = "embed-bytes"))]
    #[deprecated(note = "Feature flag not set, using empty array")]
    pub const REMOTE_FILE: &'static [u8] = &[];

    #[cfg(feature = "embed-bytes")]
    pub const ARBITRARY_DATA: &'static [u8] =
        include_bytes!(concat!(env!("OUT_DIR"), "/embed/ARBITRARY_DATA.bin"));

    #[cfg(not(feature = "embed-bytes"))]
    #[deprecated(note = "Feature flag not set, using empty array")]
    pub const ARBITRARY_DATA: &'static [u8] = &[];

}
