use bytes::Bytes;
use std::fs::{self, File};
use std::io::{self, BufWriter, Write};
use std::path::{Path, PathBuf};

pub fn write_byte_arrays(
    storage_dir: &Path,
    struct_output_path: &Path,
    struct_name: &str,
    byte_arrays: Vec<(&str, Bytes)>,
) -> io::Result<()> {
    // Ensure the storage directory exists.
    fs::create_dir_all(storage_dir)?;

    // Ensure the directory of the struct output path exists.
    if let Some(parent_dir) = struct_output_path.parent() {
        fs::create_dir_all(parent_dir)?;
    }

    // Open the Rust file for writing.
    let rs_file = File::create(struct_output_path)?;
    let mut rs_writer = BufWriter::new(rs_file);

    // Write header comments.
    writeln!(
        rs_writer,
        "// Automatically generated file. Do not edit.\n\
         // Generated by embed-bytes crate.\n"
    )?;

    // Write the struct definition.
    writeln!(rs_writer, "pub struct {};", struct_name)?;
    writeln!(rs_writer)?;

    // Write the impl block where constants are defined.
    writeln!(rs_writer, "impl {} {{", struct_name)?;
    writeln!(rs_writer)?;

    // Process each byte array.
    for (field, content) in &byte_arrays {
        let bin_filename = format!("{}.bin", field);
        let bin_path = storage_dir.join(&bin_filename);

        // Write the binary file to the storage directory.
        let mut bin_file = File::create(&bin_path)?;
        bin_file.write_all(content)?;

        // Calculate the relative path from struct output directory to binary file
        let relative_path = pathdiff::diff_paths(&bin_path, struct_output_path.parent().unwrap())
            .unwrap_or_else(|| bin_path.clone());

        // Convert the relative path to a string for include_bytes!
        let relative_str = relative_path.to_str().unwrap();

        // Write the associated constant with the correct relative path
        writeln!(
            rs_writer,
            "    pub const {}: &'static [u8] = include_bytes!(\"{}\");",
            field,
            relative_str
        )?;
    }

    // Write the closing brace for the impl block.
    writeln!(rs_writer, "}}")?;

    Ok(())
}
