use bytes::Bytes;
use std::env;
use std::fs::{self, File};
use std::io::{self, BufWriter, Write};
use std::path::{Path, PathBuf};

/// Writes binary files to `OUT_DIR/embed/` and generates a Rust struct in `src/`.
///
/// * Binary files are written to `OUT_DIR/embed/`.
/// * The generated `.rs` file is placed at `src/<struct_name>.rs`.
///
/// If the `embed-bytes` feature is enabled, the struct contains constants
/// referencing the binary files using `include_bytes!`. Otherwise, they are
/// empty arrays with a deprecation warning.
///
/// # Arguments
///
/// * `struct_output_path` - The path to `src/<struct_name>.rs`.
/// * `struct_name` - The name of the generated struct.
/// * `byte_arrays` - A vector of tuples `(field_name, content)`,
///   where `field_name` is the associated constant and `content` is the binary.
///
/// # Errors
/// Returns an `io::Error` if any file operation fails.
pub fn write_byte_arrays(
    struct_output_path: &Path,
    struct_name: &str,
    byte_arrays: Vec<(&str, Bytes)>,
) -> io::Result<()> {
    // Get OUT_DIR and resolve the binary output directory.
    let out_dir = env::var("OUT_DIR")
        .map_err(|_| io::Error::new(io::ErrorKind::NotFound, "OUT_DIR not set"))?;
    let bin_output_path = Path::new(&out_dir).join("embed");

    // Ensure binary output directory exists.
    fs::create_dir_all(&bin_output_path)?;

    // Ensure `src/` exists.
    let src_dir = Path::new("src");
    fs::create_dir_all(src_dir)?;

    // Ensure the struct output file path is within `src/`
    if !struct_output_path.starts_with("src/") {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "Struct output path must be inside `src/`.",
        ));
    }

    // Open the Rust file for writing.
    let rs_file = File::create(struct_output_path)?;
    let mut rs_writer = BufWriter::new(rs_file);

    // Write header comments.
    writeln!(
        rs_writer,
        "// Automatically generated file. Do not edit.\n\
         // Generated by embed-bytes crate.\n"
    )?;

    // Write the struct definition.
    writeln!(rs_writer, "pub struct {};", struct_name)?;
    writeln!(rs_writer)?;
    writeln!(rs_writer, "impl {} {{", struct_name)?;

    // Process each byte array.
    for (field, content) in &byte_arrays {
        let bin_filename = format!("{}.bin", field);
        let bin_path = bin_output_path.join(&bin_filename);

        // Write the binary file.
        let mut bin_file = File::create(&bin_path)?;
        bin_file.write_all(content)?;

        // Write the associated constant with conditional compilation.
        writeln!(rs_writer, "    #[cfg(feature = \"embed-bytes\")]")?;
        writeln!(rs_writer, "    pub const {}: &'static [u8] =", field)?;
        writeln!(
            rs_writer,
            "        include_bytes!(concat!(env!(\"OUT_DIR\"), \"/embed/{}\"));",
            bin_filename
        )?;
        writeln!(rs_writer)?;

        writeln!(rs_writer, "    #[cfg(not(feature = \"embed-bytes\"))]")?;
        writeln!(
            rs_writer,
            "    #[deprecated(note = \"Feature flag not set, using empty array\")]"
        )?;
        writeln!(rs_writer, "    pub const {}: &'static [u8] = &[];", field)?;
        writeln!(rs_writer)?;
    }

    writeln!(rs_writer, "}}")?;

    Ok(())
}
