[package]
name = "embed-bytes"
authors = ["Jeremy Harris <jeremy.harris@zenosmosis.com>"]
version = "0.1.0-alpha6"
edition = "2021"
repository = "https://github.com/jzombie/rust-embed-bytes"
description = "A simple Rust crate to embed assets."
license = "MIT"

[dependencies]
bytes = "1.10.0"
pathdiff = "0.2.3"
