[package]
name = "embed-resources-test-app"
version = "0.0.0"
edition = "2021"
publish = false

[features]
embed-bytes = []   # Feature flag for embedding binaries
default = ["embed-bytes"]  # Enables `embed-bytes` by default

[build-dependencies]
bytes = "1.10.0"
embed-resources = { path = "../embed-resources" }
