// Automatically generated file. Do not edit.
// Generated by embed-bytes crate.

pub struct EmbeddedData;

impl EmbeddedData {
    #[cfg(feature = "embed-bytes")]
    pub const ARRAY_ONE: &'static [u8] =
        include_bytes!(concat!(env!("OUT_DIR"), "/embed/ARRAY_ONE.bin"));

    #[cfg(not(feature = "embed-bytes"))]
    #[deprecated(note = "Feature flag not set, using empty array")]
    pub const ARRAY_ONE: &'static [u8] = &[];

    #[cfg(feature = "embed-bytes")]
    pub const ARRAY_TWO: &'static [u8] =
        include_bytes!(concat!(env!("OUT_DIR"), "/embed/ARRAY_TWO.bin"));

    #[cfg(not(feature = "embed-bytes"))]
    #[deprecated(note = "Feature flag not set, using empty array")]
    pub const ARRAY_TWO: &'static [u8] = &[];

}
