// Automatically generated file. Do not edit.
// Generated by embed-bytes crate.

pub struct EmbeddedData;

impl EmbeddedData {

    pub const ARRAY_ONE: &'static [u8] = include_bytes!("../embedded_data/ARRAY_ONE.bin");
    pub const ARRAY_TWO: &'static [u8] = include_bytes!("../embedded_data/ARRAY_TWO.bin");
}
